# -*- coding: utf-8 -*-
"""
/***************************************************************************
This script initializes the plugin, making it known to QGIS.

 Radolan2Map
                                 A QGIS plugin
 A QGIS plugin to bring a RADOLAN binary file onto a map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-05
        copyright            : (C) 2019 by Weatherman
        email                : radolan2map@e.mail.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Radolan2Map class from file Radolan2Map.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .radolan2map import Radolan2Map
    return Radolan2Map(iface)
